services:
  web:
    build: .
    volumes:
      - "./:/var/www/html"
    depends_on:
      - db
    ports:
      - "80:80"
  db:
    container_name: db
    restart: always
    image: mysql:9
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - "./database/la_couture_de_cp.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
    ports:
      - "3306:3306"
  
#   traefik:
#     image: traefik:v3.0
#     restart: always
#     command: 
#       - "--providers.docker"
#       - "--entrypoints.web.address=:80"
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#     networks:
#       - web

# networks:
#   web:
#     external: true